### PR TITLE
Rjarvinen patch 1

### PR DESCRIPTION
**Pull request by rjarvinen**

### CODE REVIEW

**Comment by iljah** [comment]
Thanks but could you fix inconsistent whitespace around line 320 in cpp? Looks like mostly spaces instead of tabs...

**Comment by rjarvinen** [comment]
> Thanks but could you fix inconsistent whitespace around line 320 in cpp? Looks like mostly spaces instead of tabs...

Done!

**Comment by iljah** [comment]
Thanks

**Comment by iljah** [comment]
Thanks

**Pull request merged**
